package org.example;

public class Enums {
    enum Category {
        BREAKFAST, LUNCH, DINNER, DESSERT, APPETIZER, SNACK, DRINK, SALAD, SOUP, SAUCE, SIDE_DISH, BREAD, PASTA, MEAT, POULTRY, SEAFOOD, VEGETABLE, FRUIT, NUT, HERB, SPICE, CONDIMENTS, BEVERAGE, NONE
    }

    enum Tag {
        SPICY, SWEET, SOUR, SALTY, BITTER, FRESH, COLD, HOT, QUICK, EASY, HARD, HEALTHY, UNHEALTHY, VEGETARIAN, VEGAN, GLUTEN_FREE // Add more as needed
    }

    enum Unit{
        GRAMS, KILOGRAMS, MILLILITERS, LITERS, PIECES, CANS, BOTTLES, PACKETS, TABLESPOONS, TEASPOONS, CUPS, PINCHES, DASHES, NONE
    }

    enum CookingInstruction {
        BAKE, BOIL, BROIL, GRILL, ROAST, SAUTE, SIMMER, STEAM, FRY, STIR_FRY, MICROWAVE, CHILL, FREEZE, THAW, MIX, STIR, BLEND, WHISK, KNEAD, ROLL, CUT, CHOP, SLICE, DICED, MINCED, GRATE, PEEL, CRUSH, MASH, SPRINKLE, GARNISH, DRIZZLE, POUR, SERVE
    }

    enum ServingSize {
        SMALL, MEDIUM, LARGE, FAMILY_SIZE
    }
}
